plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
